---
title: "USArrests"
author: "Sudisha Goswami"
date: "2025-07-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Calling the installed Libraries:

```{r usarrests, echo=TRUE, message=TRUE, warning=TRUE, paged.print=FALSE}

library(factoextra)
library(FactoMineR)
library(ggplot2)
library(ggfortify)
library(ggcorrplot)
library(gridExtra)
library(corrplot)


```

## Performing PCA on USArrests Dataset with Plotting:


```{r usarrest, echo=TRUE, message=TRUE, warning=TRUE}

USArrests.pca<-prcomp(USArrests,scale=TRUE)
summary(USArrests.pca)
fviz_eig(USArrests.pca, col.var="blue", addlabels = TRUE)
var <- get_pca_var(USArrests.pca)

corrplot(var$cos2, is.corr=FALSE)
fviz_pca_var(USArrests.pca, axes=c(1,2), col.var = "cos2", gradient.cols = c("blue", "red"), repel = TRUE)


##Below are the codings generated using ISLP book:

states <- row.names(USArrests)
states
names(USArrests)
apply(USArrests , 2, mean)
apply(USArrests , 2, var)
pr.out <- prcomp(USArrests , scale = TRUE)
names(pr.out)
pr.out$center
pr.out$rotation
dim(pr.out$x)
biplot(pr.out , scale = 0)
pr.out$rotation = -pr.out$rotation
pr.out$x = -pr.out$x
biplot(pr.out , scale = 0)
pr.out$sdev
pr.var <- pr.out$sdev^2
pr.var
pve <- pr.var / sum(pr.var)
pve
par(mfrow = c(1, 2))
plot(pve , xlab = "Principal Component",
ylab = "Proportion of Variance Explained", ylim = c(0, 1),
type = "b")
plot(cumsum(pve), xlab = "Principal Component",
ylab = "Cumulative Proportion of Variance Explained",
ylim = c(0, 1), type = "b")
a <- c(1, 2, 8, -3)
cumsum(a)
X <- data.matrix(scale(USArrests))
pcob <- prcomp(X)
summary(pcob)
sX <- svd(X)
names(sX)
round(sX$v, 3)
pcob$rotation
t(sX$d * t(sX$u))
pcob$x
nomit <- 20
set.seed (15)
ina <- sample(seq(50), nomit)
inb <- sample(1:4, nomit , replace = TRUE)
Xna <- X
index.na <- cbind(ina , inb)
Xna[index.na] <- NA
sX <- svd(X)
names(sX)
round(sX$v, 3)
pcob$rotation
t(sX$d * t(sX$u))
pcob$x
nomit <- 20
set.seed (15)
ina <- sample(seq(50), nomit)
inb <- sample(1:4, nomit , replace = TRUE)
Xna <- X
index.na <- cbind(ina , inb)
Xna[index.na] <- NA
fit.svd <- function(X, M = 1){
svdob <- svd(X)
with(svdob,
u[, 1:M, drop = FALSE] %*%
(d[1:M] * t(v[, 1:M, drop = FALSE]))
)
}
fit.svd

Xhat <- Xna
xbar <- colMeans(Xna , na.rm = TRUE)
Xhat[index.na] <- xbar[inb]
thresh <- 1e-7
rel_err <- 1
iter <- 0
ismiss <- is.na(Xna)
mssold <- mean((scale(Xna , xbar , FALSE)[!ismiss])^2)
mss0 <- mean(Xna[!ismiss]^2)


```

## Thank You
